In [1]:
import pandas as pd
import json
from pycaret.classification import *

In [22]:
pd.set_option('display.max_columns', None)

In [4]:
train_stats = pd.read_csv('../data/train_demo.csv')

In [23]:
train_stats

,matchId,teamId,participantId,summonerId,championId,winner,team100_winrates,team200_winrates,team100_pickrates,team200_pickrates,team100_banrates,team200_banrates,"('mean', 100)","('mean', 200)","('median', 100)","('median', 200)","('<lambda_0>', 100)","('<lambda_0>', 200)","('skew', 100)","('skew', 200)","('std', 100)","('std', 200)","('var', 100)","('var', 200)",100,200,championLevel_100,championLevel_200,championPoints_100,championPoints_200,summonerLevel_100,summonerLevel_200,tag_count_100_sum,tag_count_200_sum,team100_totalGold,team200_totalGold,team100_totalDamageDoneToChampions,team200_totalDamageDoneToChampions,team100_minionsKilled,team100_jungleMinionsKilled,team200_minionsKilled,team200_jungleMinionsKilled,team200_killStreakLength,team100_killStreakLength,team200_dragonsKilled,team100_dragonsKilled
0,0,100,1,0,82,200,0.493720,0.496060,0.059667,0.060800,0.1070,0.0738,6.0,6.0,6.0,7.0,2.000000,-1.750000,0.000000,-0.883883,0.707107,1.414214,0.5,2.0,0.857143,0.857143,30.0,30.0,844882.0,1450310.0,2771.0,2089.0,7.0,9.0,141460,175390,34460,42570,9420.0,2630.0,10850.0,2430.0,120.0,0.0,10.0,0.0
1,1,100,1,10,92,200,0.496920,0.507143,0.082700,0.098067,0.1284,0.1148,6.6,5.0,7.0,4.0,5.000000,-2.897959,-2.236068,0.381802,0.894427,1.870829,0.8,3.5,0.942857,0.714286,33.0,25.0,2227610.0,871583.0,2213.0,1585.0,9.0,8.0,176620,148160,13650,40900,10160.0,3030.0,11090.0,3000.0,10.0,20.0,10.0,0.0
2,2,100,1,20,266,200,0.496480,0.497867,0.081400,0.065533,0.1848,0.2002,5.0,4.8,5.0,4.0,-3.000000,-3.163265,0.000000,0.441479,2.000000,2.049390,4.0,4.2,0.714286,0.685714,25.0,24.0,391340.0,665251.0,2119.0,1070.0,8.0,9.0,163740,173470,29630,29410,8910.0,3160.0,9180.0,2680.0,30.0,40.0,0.0,10.0
3,3,100,1,30,875,100,0.496180,0.496000,0.061200,0.122900,0.0620,0.0776,5.6,6.2,6.0,7.0,-3.081285,2.664360,-0.315356,-1.714392,1.516575,1.303840,2.3,1.7,0.800000,0.885714,28.0,31.0,640810.0,928477.0,1624.0,2651.0,9.0,8.0,192470,151450,21710,30290,9340.0,2580.0,8910.0,2520.0,10.0,110.0,0.0,10.0
4,4,100,1,40,39,200,0.509230,0.489970,0.055500,0.064600,0.0890,0.1194,5.6,4.2,5.0,5.0,-2.407407,-3.333333,0.165635,-0.608581,1.341641,1.095445,1.8,1.2,0.800000,0.600000,28.0,21.0,645519.0,141851.0,2232.0,620.0,8.0,8.0,167760,153850,39990,26860,10520.0,3300.0,10620.0,2550.0,10.0,20.0,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7995,100,1,1283,145,200,0.492980,0.502597,0.081300,0.024067,0.0688,0.0304,6.0,6.0,6.0,7.0,-3.000000,5.000000,0.000000,-2.236068,1.000000,2.236068,1.0,5.0,0.857143,0.857143,30.0,30.0,1243322.0,1411140.0,2835.0,2727.0,8.0,10.0,190090,148730,41940,17980,12170.0,3160.0,9470.0,3110.0,10.0,70.0,10.0,0.0
7996,7996,100,1,37425,54,100,0.504500,0.499480,0.104133,0.063000,0.0904,0.0688,5.6,6.0,7.0,7.0,-2.479224,-1.750000,-0.755984,-0.883883,1.949359,1.414214,3.8,2.0,0.800000,0.857143,28.0,30.0,1301721.0,557302.0,1665.0,2457.0,10.0,9.0,164130,161400,55070,26470,9850.0,2900.0,10250.0,2840.0,10.0,40.0,10.0,0.0
7997,7997,100,1,1190,6,200,0.507400,0.497700,0.081500,0.097900,0.0958,0.0442,5.8,5.8,7.0,7.0,0.312500,4.151200,-1.257788,-2.031531,1.788854,2.167948,3.2,4.7,0.828571,0.828571,29.0,29.0,664485.0,1203774.0,1558.0,1055.0,9.0,9.0,177450,165710,33540,30020,8490.0,1520.0,8980.0,2880.0,40.0,30.0,10.0,0.0
7998,7998,100,1,29798,98,200,0.511870,0.498745,0.109000,0.041600,0.0558,0.0600,5.2,6.4,7.0,7.0,0.312500,5.000000,-1.257788,-2.236068,2.683282,1.341641,7.2,1.8,0.742857,0.914286,26.0,32.0,290251.0,703659.0,1881.0,2850.0,7.0,9.0,155430,183110,25600,80720,9530.0,2910.0,11100.0,3040.0,20.0,30.0,10.0,0.0
7999,7999,100,1,4970,420,100,0.499233,0.502883,0.049800,0.025733,0.0608,0.0526,5.2,5.4,5.0,6.0,0.918367,4.225246,-1.022372,-2.017344,2.049390,2.509980,4.2,6.3,0.742857,0.771429,26.0,27.0,3962209.0,301991.0,2461.0,2438.0,10.0,10.0,170580,148920,20750,33600,10440.0,2890.0,10600.0,2240.0,0.0,30.0,0.0,0.0

In [5]:
test_stats = pd.read_csv('../data/test_demo.csv')

In [26]:
# initialize setup and target
clf1 = setup(data=train_stats, target='winner')

# compare models and select the best one
best_model = compare_models()

# predict the winners for the test data using the best model
predictions = predict_model(best_model, data=test_stats)

# generate matchId numbers from 8000 to 9999 for the test set
predictions['matchId'] = range(8000, 8000+len(test_stats), 1)
predictions = predictions[['matchId', 'prediction_label']]

# rename the predicted winner column
predictions = predictions.rename(columns={'prediction_label': 'winner'})
predictions

Processing:   0%|          | 0/69 [00:00<?, ?it/s]

      matchId  winner
0        8000     100
1        8001     100
2        8002     200
3        8003     200
4        8004     200
...       ...     ...
1995     9995     100
1996     9996     100
1997     9997     200
1998     9998     100
1999     9999     100

[2000 rows x 2 columns]

In [27]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [ ]:
# export csv for kaggle submission 
predictions.to_csv('predictions.csv', index=False)